version: '3'
services:
  nginx:
    container_name: nginx-server
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/common.conf:/etc/nginx/common.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/app_data:/var/www/html
    depends_on:
      - nextcloud
      - onlyoffice
    networks:
      - nextcloud_network

  nextcloud:
    container_name: nextcloud-local
    image: nextcloud:fpm
    restart: always
    environment:
      - POSTGRES_HOST=dbpostgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    expose:
      - '80'
      - '9000'
    volumes:
      - ./volumes/app_data:/var/www/html
    depends_on:
      - dbpostgres
    networks:
      - nextcloud_network
  
  onlyoffice:
    container_name: onlyoffice-local
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - DB_TYPE=postgres
      - DB_HOST=dbpostgres
      - DB_PORT=5432
      - DB_NAME=nextcloud
      - DB_USER=postgres
      - DB_PWD=pass
      - JWT_SECRET=O9aFioQOAxc4SB4P1IaKe6JOyiq5WgCM
    expose:
      - '80'
      - '443'
    volumes:
      - ./volumes/document_data:/var/www/onlyoffice/Data
      - ./volumes/document_log:/var/log/onlyoffice
    depends_on:
      - dbpostgres
    networks:
      - nextcloud_network
  
  dbpostgres:
    image: postgres:latest
    container_name: dbpostgres
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    expose:
      - "5432"
    volumes:
      - ./volumes/db_data:/var/lib/postgresql/data
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
